pipeline {
            agent { label 'Jenkins node' }
            tools {
                      maven:'mvn3.9'
            }
        stages {
              stage('source') { 
                  steps { 
                      git url:"https://github.com/Nisarga23nisu/simple-java-maven-app.git"
                        branch: 'master'
        stages ('package'){
               steps{
                        sh 'mvn package' 
            }
        }
     }   
}



*/pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}/*
